### ISSUE TITLE
Option to maintain provider cache?

### ISSUE THREAD

**Issue by bricoletc** [vanheeringen-lab/genomepy#230]
Hello!

I see from README that `The cached files are stored in ~/.cache/genomepy and expire after 7 days. ` 

Any way to specify e.g. on CLI that I'm fine with a given freeze of the list of genomes, and use the cache as is, even if it's >7 days old?

In fact, why is that not the default?

Thanks

**Comment by siebrenf** [comment]
Hey @bricoletc,

we originally did this because new assemblies are uploaded regularly (mainly on NCBI). A regular snapshot is also the easiest way to stay up to date with internal changes of provider databases (Ensembl likes to change stuff between releases).

I've moved the expiration timer(s) to the configuration file in #231, so you can freeze or extended the expiration timer! This might cause more issues.

P.S. Something broke over on Travis, so I'll merge this PR when its fixed.

**Comment by bricoletc** [comment]
Great, looking forward to seeing it in next release ! Thanks and best

**Comment by siebrenf** [comment]
genomepy 0.15 (with this feature) will be up on Bioconda soon!

**Comment by bricoletc** [comment]
Could you indicate how the cache time should be specified in the config file? And more generally, a list of all possible config keys in the README.md or other documentation file?

**Comment by siebrenf** [comment]
Good point! I've added a [page](https://vanheeringen-lab.github.io/genomepy/content/config.html) to the docs with details.
